"""
Regenerates docs/function_index.md from AST parsing of all tool modules.
Run from the odoo-mcp/ directory: python scripts/gen_index.py
"""
import ast
import inspect
import os
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
SCAN_FILES = [
    "tools/read.py",
    "tools/write.py",
    "tools/utils.py",
]
OUTPUT = ROOT / "docs" / "function_index.md"


def extract_functions(filepath: Path) -> list[dict]:
    source = filepath.read_text(encoding="utf-8")
    tree = ast.parse(source)
    results = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.AsyncFunctionDef, ast.FunctionDef)):
            continue
        if node.name.startswith("_"):
            continue
        # Build signature string
        args = []
        func_args = node.args
        defaults = func_args.defaults
        all_args = func_args.args
        # Align defaults to the end of args list
        default_offset = len(all_args) - len(defaults)
        for i, arg in enumerate(all_args):
            if arg.arg == "self":
                continue
            annotation = ""
            if arg.annotation:
                annotation = f": {ast.unparse(arg.annotation)}"
            default = ""
            if i >= default_offset:
                d = defaults[i - default_offset]
                default = f" = {ast.unparse(d)}"
            args.append(f"{arg.arg}{annotation}{default}")
        sig = f"({', '.join(args)})"
        # Return annotation
        ret = ""
        if node.returns:
            ret = f" → {ast.unparse(node.returns)}"
        # First line of docstring
        doc = ast.get_docstring(node) or ""
        first_line = doc.split("\n")[0].strip() if doc else ""
        results.append({
            "name": node.name,
            "sig": sig,
            "ret": ret,
            "doc": first_line,
        })
    return results


def main():
    rows = []
    for rel_path in SCAN_FILES:
        filepath = ROOT / rel_path
        for fn in extract_functions(filepath):
            rows.append({**fn, "file": rel_path})

    lines = [
        "# Function Index",
        "",
        "_Auto-generated by `scripts/gen_index.py` — do not edit manually._",
        "",
        "| Function | File | Signature | Description |",
        "|---|---|---|---|",
    ]
    for r in rows:
        sig_display = f"`{r['name']}{r['sig']}{r['ret']}`"
        lines.append(f"| `{r['name']}` | `{r['file']}` | {sig_display} | {r['doc']} |")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Written {len(rows)} functions to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
